= Glykon OZG Modeler
:toc:

Modeler for OZG reference data fields and mask Information.

== Features

* Reads XDatenfelder definition files as JSON
* Uses pluggable JSONata template to generate form specification files for OZG online process platforms.

XDatenfelder mapping to JSON is provided by Jsonix.

== Roadmap

User interface for editing

== Usage

For now, this demo just reads the example XDatenfelder definition in  _bewohnerparken/S05000058V1.0_xdf2.xml_ and uses _jsonata/example-formtemplate.jsonata_ to log a sample form definition json in the console.

Execute index.js in node.js V14.16.1 or later:

* Install Node
* Run `npm install` inside this repository
* Run `node path/to/index.js`

== Why Glykon?

Since OZG Tooling often seems to reference ancient greek celebrities and the task set forth by OZG can appear herculean at times, I chose Glykon, the sculptor of the famous https://en.wikipedia.org/wiki/Farnese_Hercules[Ercole Farnese] statue.

[quote, Wikipedia, Farnese Hercules]
It depicts a muscular, yet weary, Hercules leaning on his club, which has the skin of the Nemean lion draped over it. In myths about Heracles, killing the lion was his first task. He has just performed one of the last of The Twelve Labours, which is suggested by the apples of the Hesperides he holds behind his back.