= Glykon Sculptor for OZG
:toc:

Modeler for OZG reference data fields and mask Information with pluggable form generation.

== Features

* Allows to edit XDatenfelder to derive an OZG Referenzdatenschema from FIM Stammdatenschema.
* Generates JSON Form descriptors by applying a given JSONata template to OZG Referenzdatenschema

== Roadmap

* User interface to edit mask information, see https://github.com/escalon/glykon/issues[Issues].
* Support for version upgrade.
* Electron app and Webcomponent building upon the current Svelte Component

== Usage
* Install Node v14.16.1 or later
* Run `npm install` inside this repository
* Run `npm run dev`

== Why Glykon?

Since OZG Tooling often seems to reference ancient greek celebrities and the task set forth by OZG can appear herculean at times, I chose Glykon, the sculptor of the famous https://en.wikipedia.org/wiki/Farnese_Hercules[Ercole Farnese] statue.

[quote, Wikipedia, Farnese Hercules]
It depicts a muscular, yet weary, Hercules leaning on his club, which has the skin of the Nemean lion draped over it. In myths about Heracles, killing the lion was his first task. He has just performed one of the last of The Twelve Labours, which is suggested by the apples of the Hesperides he holds behind his back.